/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado;

import eldorado.gamemanager.ElDoradoManager;
import eldorado.gamemanager.MarketManager;
import eldorado.utils.HexMapBuilder;
import eldorado.utils.MapGenerator;
import eldorado.utils.json.MapReader;

import org.junit.Test;

public class GenerateMapTest {

    private ElDoradoManager elDoradoManager;
    private MarketManager shopManager;

    @Test
    public void generateNewMap() {
        HexMapBuilder hexMapBuilder = new HexMapBuilder();
        MapGenerator mapGenerator = new MapGenerator();
        MapReader mapReader = new MapReader();
        ElDoradoManager.initializeInstance(hexMapBuilder, mapGenerator, mapReader, false, false);

        elDoradoManager = (ElDoradoManager) ElDoradoManager.getInstance();
        shopManager = MarketManager.getInstance();
        shopManager.shopManagement().createShop();
        shopManager.stockManagement().createStock();

        // Clear players list before each test
        elDoradoManager.reset(false);
    }

    @Test
    public void generateOldMap() {
        HexMapBuilder hexMapBuilder = new HexMapBuilder();
        MapGenerator mapGenerator = new MapGenerator();
        MapReader mapReader = new MapReader();
        ElDoradoManager.initializeInstance(hexMapBuilder, mapGenerator, mapReader, true, false);

        elDoradoManager = (ElDoradoManager) ElDoradoManager.getInstance();
        shopManager = MarketManager.getInstance();
        shopManager.shopManagement().createShop();
        shopManager.stockManagement().createStock();

        // Clear players list before each test
        elDoradoManager.reset(false);
    }
}
